--- 
title: "Lockdown to R-Full-stack"
author: "Richard Nacianceno"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is my journey to R programming."
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(emo)
```

# Overview {-}

This is my journey during Covid-19 lockdown in the US and how I was able to learn R programming through Coursera - JHU Data Science Specialization [@dss]. I enrolled for the course in March of 2020 and I will provide the "ah-ha" moment of my journey.

The program consists of 10 courses that covers the following:

1. **The Data Scientist’s Toolbox**
2. **R Programming**
3. **Getting and Cleaning Data**
4. **Exploratory Data Analysis**
5. **Reproducible Research**
6. **Statistical Inference**
7. **Regression Models**
8. **Practical Machine Learning**
9. **Developing Data Products**
10. **Data Science Capstone**

As of today, July 29, 2020 I'm currently at course 10 Data Science Capstone - Week 1. The entire data science specialization can be completed in less than 11 months based on your desire to learn. I've put in an average of 5 hours per day in each courses. The reason I wanted to learn these materials so fast are as follows: 

- Personal growth 
- Love dissecting data for insights
- The course syllabus is well though-out 
- Professors bringing their expertise in their respective field
- Professors abilities to communicate and teach the courses is simple and concise.

Professor Roger D. Peng, PhD, Professor Brian Caffo, PhD and Professor Jeff Leek, PhD - from the bottom of my heart - thank you so much. 

## Expect To Have Lucid Dreams {-}

<div align="center">“I had a dream about you. It's been a while<br>since I could remember any of my dreams,<br>and still, this one has left me with such strong impression.<br>[@ninkovic]"</div>
<br>

That quote from Aleksandra is one of the many stories that occurred to me while taking these courses. It is not easy. You need perseverance and continuously seeking knowledge. There were nights that turned to days and nights to day and back to night because I could not figure out how to solve a problem. My brain was constantly looking for a solution. Once you solved it, you then moved on to the next challenge with the same twist of time. It gets better `r emo::ji("smile")` [@emo].

There was no way for me to complete this program without the help of [google.com](https://google.com), Yihue Xie, PhD - books, Professor Handley Wickham, PhD - books and to all the people that contributed to [stackoverflow](https://stackoverflow.com/) - Thank You.  

## Retrospect {-}

If I could do it all over again. I would add the following courses, tools and skills on top of the specialization which are as follows:

1. Get Linux Ubuntu 20.04 LTS Desktop as your main environment [@ubuntu].  I initially started with Microsoft Windows 10.  The experience was awful. After the Windows 10 update, it would not let me write on my disk while running RStudio. This added to the frustration and sleepless nights. Linux Ubuntu 20.04 LTS is the most stable environment for **me**.  
2. Learn the bash through Cousera course The Unix Workbench by Sean Kross which provides a powerful insight of the inner working of linux accompanied with Git/Github for version control [@unix].
3. Learn blogdown or bookdown packages for proper documentation. There were many days that I have to find saved assignment in my hard-drive. These packages will  organize your thought process and force you to have a central location. Now, that I have the power of blogdown/bookdown together with github, these provides a central place where I can organize my work and have a version control. These are very valuable tools to learn.     
4. Once complete your specialization using either bookdown or blogdown packages.  

I wish I can go back in-time and start the process with these 3 steps first before jumping into Data Science Specialization.
